# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('acceuil', 'acceuil'), ('presentation', 'presentation'), ('education', 'education'), ('tarifs', 'tarifs'), ('contact', 'contact')], max_length=200)),
                ('left', models.CharField(max_length=900)),
                ('right', models.CharField(max_length=900)),
            ],
        ),
    ]
