# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_contact_codepostal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='codePostal',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='contact',
            name='telephone',
            field=models.CharField(max_length=10),
        ),
    ]
