# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20160319_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('detail', models.CharField(max_length=600)),
                ('prix', models.IntegerField()),
            ],
        ),
    ]
