# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_tarif'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='file',
            field=models.FileField(default=1, upload_to='static/img'),
            preserve_default=False,
        ),
    ]
